name: 'Terraform Github Actions'
default: 
  run:
    working-directory: "testrun"
on:
  - pull_request
  - push
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: 'Terraform Init'
      id: init
      run: terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Terraform Validate"
      id: validate
      run: terraform validate
