name: 'Terraform Github Actions'
defaults: 
  run:
    working-directory: "testrun"
on:
  - pull_request
  - push
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      TF_VAR_client_id: ${{ secrets.TF_VAR_client_id}}
      TF_VAR_client_secret: ${{ secrets.TF_VAR_client_secret }}
      TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
      TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}

    steps:
      - uses: actions/checkout@v2
      - name: 'Terraform Init'
        id: init
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Terraform Validate"
        id: validate
        run: terraform validate
  
      - name: 'Terraform Apply'
        id: apply
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
